#### TensorFlow Importing Package

In [ ]:
import tensorflow as tf

print(tf.__version__)

#### TensorFlow Constant and TensorFlow Variable

**```tf.constant()``` is a special variable where you only can defined it once**

In [ ]:
var_zero = tf.constant(10)

print(var_zero)

In [ ]:
var_one = tf.constant([10])

print(var_one)

In [4]:
var_two = tf.constant([[10,10]])

print(var_two)

tf.Tensor([[10 10]], shape=(1, 2), dtype=int32)


In [5]:
var_two1 = tf.constant(
    [[10,10,10]])

print(var_two1)

tf.Tensor([[10 10 10]], shape=(1, 3), dtype=int32)


In [6]:
var_two2 = tf.constant(
    [[1,2],
     [3,4]])

print(var_two2)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
var_two3 = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

print(var_two3)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [8]:
var_list = tf.constant([*range(1,6)])

print(var_list)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [9]:
var_list2 = tf.constant([[*range(1,6)],[*range(6,11)]])

print(var_list2)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


**```tf.Variable()``` is a variable that you can defined it more than once**

In [10]:
var_zero = tf.Variable(10)

print(var_zero)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [11]:
var_one = tf.Variable([10])

print(var_one)

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([10], dtype=int32)>


In [12]:
var_twov = tf.Variable([[1,2],[3,4]])

print(var_two)

tf.Tensor([[10 10]], shape=(1, 2), dtype=int32)


In [13]:
chng_x = tf.Variable(10)

print(chng_x)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [14]:
try:
    chng_x.assign(50)
    print(chng_x)
except:
    print("Unavailable Method !")

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=50>


In [15]:
cnst_x = tf.constant(50)

try:
    cnst_x.assign(100)
    print(cnst_x)
except:
    print("Unavailable method !")

Unavailable method !


**Create special random tensor**

**```tf.random.uniform()``` is a special method to create a random tensor based on Uniform Distribution**

In [16]:
# shape, minval, maxval
random_uniform = tf.random.uniform(shape=[2,2], minval=1, maxval=4)

print(random_uniform)

tf.Tensor(
[[2.6043315 2.5451856]
 [1.4255922 2.1423936]], shape=(2, 2), dtype=float32)


In [17]:
# shape, minval, maxval
random_uniform = tf.random.uniform(shape=[2,2], minval=1, maxval=4, dtype=tf.int32)

print(random_uniform)

tf.Tensor(
[[2 1]
 [3 1]], shape=(2, 2), dtype=int32)


In [18]:
random_uniform = tf.random.uniform(shape=[2,2], minval=1, maxval=4, dtype=tf.int32)

print(random_uniform)

tf.Tensor(
[[1 1]
 [2 3]], shape=(2, 2), dtype=int32)


In [19]:
tf.random.set_seed(42)

rand_uniform = tf.random.uniform(shape=[1,2])

print(rand_uniform)

tf.Tensor([[0.6645621  0.44100678]], shape=(1, 2), dtype=float32)


In [20]:
tf.random.set_seed(42)

rand_uniform = tf.random.uniform(shape=[1,2])

print(rand_uniform)

tf.Tensor([[0.6645621  0.44100678]], shape=(1, 2), dtype=float32)


**```tf.random.normal()``` is a special method to create a random tensor based on Normal Distribution**

In [21]:
rand_norm = tf.random.normal(shape=[2,2], mean=0, stddev=1)

print(rand_norm)

tf.Tensor(
[[ 0.08422458 -0.86090374]
 [ 0.37812304 -0.00519627]], shape=(2, 2), dtype=float32)


In [22]:
tf.random.set_seed(10)

rand_norm = tf.random.normal(shape=[2,2], mean=0, stddev=1)

print(rand_norm)

tf.Tensor(
[[-0.8757808   0.3356369 ]
 [-0.35219625 -0.3031456 ]], shape=(2, 2), dtype=float32)


In [23]:
tf.random.set_seed(10)

rand_norm = tf.random.normal(shape=[2,2], mean=0, stddev=1)

print(rand_norm)

tf.Tensor(
[[-0.8757808   0.3356369 ]
 [-0.35219625 -0.3031456 ]], shape=(2, 2), dtype=float32)


**Create special Tensor**

In [24]:
one = tf.ones([2,2], dtype=tf.int32)

print(one)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [1]:
zero = tf.zeros([2,2])

print(zero)

NameError: name 'tf' is not defined

**Create Tensor from Numerical Python**

In [26]:
import numpy as np

arr = np.array([*range(1,6)])
tf_arr = tf.Variable(arr)

print(tf_arr)

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([1, 2, 3, 4, 5])>


**Get information from Tensor**

In [27]:
var_rand = tf.constant([[1,2,3],[4,5,6]])

print(var_rand)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [28]:
print(var_rand.ndim)

2


In [29]:
print(var_rand.shape)

(2, 3)


In [30]:
print(var_rand.numpy())

[[1 2 3]
 [4 5 6]]


In [31]:
rand = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

print(rand)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


**Accessing Tensor**

In [32]:
print(rand[0])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [33]:
print(rand[:1])

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [34]:
print(rand[0:2])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [35]:
print(rand[:,0])

tf.Tensor([1 4 7], shape=(3,), dtype=int32)


In [36]:
print(rand[1,1])

tf.Tensor(5, shape=(), dtype=int32)


**Tensor Operation**

In [37]:
tf_1 = tf.constant([*range(1,10,2)])
tf_2 = tf.constant([*range(9,0,-2)])

print(tf_1)
print(tf_2)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([9 7 5 3 1], shape=(5,), dtype=int32)


In [38]:
print(tf_1 + 1)

tf.Tensor([ 2  4  6  8 10], shape=(5,), dtype=int32)


In [39]:
print(tf_1 - 1)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [40]:
print(tf_1 * 10)

tf.Tensor([10 30 50 70 90], shape=(5,), dtype=int32)


In [41]:
print(tf_1 / 2)

tf.Tensor([0.5 1.5 2.5 3.5 4.5], shape=(5,), dtype=float64)


In [42]:
print(tf.math.add(tf_1, tf_2))

tf.Tensor([10 10 10 10 10], shape=(5,), dtype=int32)


In [43]:
print(tf.math.subtract(tf_1, tf_2))

tf.Tensor([-8 -4  0  4  8], shape=(5,), dtype=int32)


In [44]:
print(tf.math.multiply(tf_1,10))

tf.Tensor([10 30 50 70 90], shape=(5,), dtype=int32)


In [45]:
print(tf.math.multiply(tf_1, tf_2))

tf.Tensor([ 9 21 25 21  9], shape=(5,), dtype=int32)


In [46]:
print(tf.math.minimum(tf_1, tf_2))

tf.Tensor([1 3 5 3 1], shape=(5,), dtype=int32)


In [47]:
print(tf.math.maximum(tf_1, tf_2))

tf.Tensor([9 7 5 7 9], shape=(5,), dtype=int32)


In [48]:
tf_x = tf.constant([[1,2],[3,4]])
tf_y = tf.constant([[5,6],[7,8]])

print(tf.linalg.matmul(tf_x, tf_y))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [49]:
print(tf_x @ tf_y)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [50]:
tf_rand = tf.random.uniform(shape=[2,3])

print(tf_rand)

tf.Tensor(
[[0.55478156 0.42658198 0.14140713]
 [0.703694   0.3726666  0.6976985 ]], shape=(2, 3), dtype=float32)


**Tensor Reshape**

In [51]:
tf_rand_reshape = tf.reshape(tf_rand, shape=(3,2))

print(tf_rand_reshape)

tf.Tensor(
[[0.55478156 0.42658198]
 [0.14140713 0.703694  ]
 [0.3726666  0.6976985 ]], shape=(3, 2), dtype=float32)


In [52]:
print(tf.transpose(tf_rand_reshape))

tf.Tensor(
[[0.55478156 0.14140713 0.3726666 ]
 [0.42658198 0.703694   0.6976985 ]], shape=(2, 3), dtype=float32)


In [53]:
arr = tf.constant(np.random.randint(0,20, size=10))
print(arr)

tf.Tensor([ 0  8  0  4 18  3  5 14 14  3], shape=(10,), dtype=int64)


**Aggregate Tensor**

In [54]:
print(tf.reduce_min(arr))
print(tf.reduce_max(arr))
print(tf.reduce_mean(arr))
print(tf.math.argmax(arr))
print(tf.math.argmin(arr))

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(18, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


**One Hot Encoding**

In [55]:
# One hot encoding
food = [0,1,2]
tf.one_hot(food, depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>