*y = 50x + 50*

In [1]:
import numpy as np
import tensorflow as tf

print(np.__version__)
print(tf.__version__)

1.21.5
2.8.0


In [2]:
beds = np.array([*range(1,7)], dtype=np.float16)
prices = np.array([(bed * 50000) + 50000 for bed in beds])

print(beds)
print(prices)

[1. 2. 3. 4. 5. 6.]
[100000. 150000. 200000. 250000. 300000. 350000.]


In [3]:
X, y = tf.constant(beds), tf.constant(prices)

print(X)
print(y)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float16)
tf.Tensor([100000. 150000. 200000. 250000. 300000. 350000.], shape=(6,), dtype=float64)


In [4]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(1, input_shape=[1])
])

model.compile(loss=tf.keras.losses.mse,
              optimizer=tf.keras.optimizers.SGD())

In [5]:
model.fit(X, y, epochs=1000, verbose=0)

In [6]:
model.predict([7.0])

array([[400596.16]], dtype=float32)